backend:
  name: github
  repo: KamilaZalewska/ckp-pirania
  branch: main
  
local_backend: true
publish_mode: editorial_workflow

oauth:
  provider: github
  redirect_uri: https://ckp-pirania.netlify.app/admin/

media_folder: "photos/aktualnosci"
public_folder: "/photos/aktualnosci"

collections:
  - name: "aktualnosci"
    label: "Aktualności"
    folder: "content/aktualnosci"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Lead", name: "lead", widget: "text" }
      - { label: "Treść", name: "body", widget: "markdown" }
      - { label: "Zdjęcie główne", name: "image", widget: "image" }